name: deployin to aws uWu!

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Dev
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: installing nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: building application
      run : |
        npm install
        npm run build
    
    - name: copying files in a single folder
      run: |
        mkdir s3
        cp -r scripts s3
        cp -r dist s3
        cp -r public s3
        cp appspec.yml s3

    - name: checking what's in s3 folder
      run: ls s3
    


    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_REGION_DEV }}